compatibility_date = "2023-03-14"
name = "api"
main = "index.js"
compatibility_flags = [ "nodejs_compat" ]
account_id = "424ad63426a1ae47d559873f929eb9fc"
workers_dev = true
routes = ["api.tarkov.dev/graphql", "api.tarkov.dev/graphql*", "api.tarkov.dev/___graphql", "api.tarkov.dev/webhook*", "streamer.tarkov.dev/*"]
kv_namespaces = [
    { binding = "DATA_CACHE", id = "2e6feba88a9e4097b6d2209191ed4ae5", preview_id = "17fd725f04984e408d4a70b37c817171" },
    { binding = "QUERY_CACHE", id = "cf717460f7eb40299a0f8f844d157051", preview_id = "cf717460f7eb40299a0f8f844d157051" }
]

[env.development]
routes = []
kv_namespaces = [
    { binding = "DATA_CACHE", id = "17fd725f04984e408d4a70b37c817171", preview_id = "17fd725f04984e408d4a70b37c817171" },
    { binding = "QUERY_CACHE", id = "cf717460f7eb40299a0f8f844d157051", preview_id = "cf717460f7eb40299a0f8f844d157051" }
]

# [secrets]
# CACHE_BASIC_AUTH
# TWITCH_CLIENT_ID
# TWITCH_TOKEN

[env.production.vars]
TRACE_SAMPLE_RATE = 0.05
ENVIRONMENT = "production"
# We should set this to the commit hash on deploy
VERSION = "1.0"

[env.development.vars]
TRACE_SAMPLE_RATE = 1
ENVIRONMENT = "development"
# We should set this to the commit hash on deploy
VERSION = "1.0-dev"
