compatibility_date = "2021-12-14"
name = "api"
type = "webpack"
account_id = "424ad63426a1ae47d559873f929eb9fc"
zone_id = "777d475095752ccbe5d1d49e690a305b"
workers_dev = true
webpack_config = "webpack.config.js"

[env.production]
routes = ["api.tarkov.dev/graphql", "api.tarkov.dev/graphql*", "api.tarkov.dev/___graphql", "api.tarkov.dev/webhook*"]
kv-namespaces = [
    { binding = "DATA_CACHE", id = "2e6feba88a9e4097b6d2209191ed4ae5", preview_id = "17fd725f04984e408d4a70b37c817171" },
    { binding = "QUERY_CACHE", id = "7ae67967cff24ceaa31ca58c5a6da798", preview_id = "cf717460f7eb40299a0f8f844d157051" }
]
vars = { ENVIRONMENT = "production" }

[env.staging]
routes = ["dev.api.tarkov.dev/graphql", "dev.api.tarkov.dev/graphql*", "dev.api.tarkov.dev/___graphql", "dev.api.tarkov.dev/webhook*"]
kv-namespaces = [
    { binding = "DATA_CACHE", id = "17fd725f04984e408d4a70b37c817171", preview_id = "17fd725f04984e408d4a70b37c817171" },
    { binding = "QUERY_CACHE", id = "cf717460f7eb40299a0f8f844d157051", preview_id = "cf717460f7eb40299a0f8f844d157051" }
]
#vars = { ENVIRONMENT = "staging" }

[env.development]
kv-namespaces = [
    { binding = "DATA_CACHE", id = "2e6feba88a9e4097b6d2209191ed4ae5", preview_id = "17fd725f04984e408d4a70b37c817171" },
    { binding = "QUERY_CACHE", id = "7ae67967cff24ceaa31ca58c5a6da798", preview_id = "cf717460f7eb40299a0f8f844d157051" }
]
vars = { ENVIRONMENT = "development" }

# [secrets]
# CACHE_BASIC_AUTH
