name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # pin@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Publish - Production
        uses: cloudflare/wrangler-action@3424d15af26edad39d5276be3cc0cc9ffec22b55 # pin@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}

      # Send a deployment message to Discord via a webhook
      - name: Discord notification
        if: github.event_name == 'push'
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9 # pin@0.3.2
        with:
          args: "The project `{{ EVENT_PAYLOAD.repository.full_name }}` has been
            **deployed** to **production** 🚀"
