name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # pin@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # pin@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Publish - Production
        uses: cloudflare/wrangler-action@3424d15af26edad39d5276be3cc0cc9ffec22b55 # pin@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
