name: Deploy

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  deploy:
    steps:
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: "production"
